"""fixed foreign_key

Revision ID: 8e8516771f86
Revises: 8317896bdbab
Create Date: 2026-07-05 17:58:50.960900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8516771f86'
down_revision: Union[str, Sequence[str], None] = '8317896bdbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'place', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'place', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.drop_constraint(None, 'place', type_='foreignkey')
    # ### end Alembic commands ###
