"""fixed Place models

Revision ID: c01897c5d9fb
Revises: 68c19ba6c978
Create Date: 2026-07-06 10:01:17.265407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01897c5d9fb'
down_revision: Union[str, Sequence[str], None] = '68c19ba6c978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('place', sa.Column('is_visited', sa.Boolean(), nullable=False))
    op.drop_column('project', 'notes')
    op.drop_column('project', 'is_visited')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_visited', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('place', 'is_visited')
    op.drop_column('place', 'notes')
    # ### end Alembic commands ###
